services:
  uniterm_db:
    image: mysql:8.4
    container_name: uniterm_db
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uniterms
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_TCP_PORT: 3000
    volumes:
      - uniterm_db_volumes:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  uniterm_db_volumes:
    driver: local
